# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 2.8

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files (x86)\CMake 2.8\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files (x86)\CMake 2.8\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "C:\Program Files (x86)\CMake 2.8\bin\cmake-gui.exe"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\varsha\Documents\ResearchTools\head_pose_estimation\demo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\varsha\Documents\ResearchTools\head_pose_estimation\my_demo_build

# Include any dependencies generated for this target.
include CMakeFiles/../head_pose_estimation_demo.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/../head_pose_estimation_demo.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/../head_pose_estimation_demo.dir/flags.make

CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRForestEstimator.cpp.obj: CMakeFiles/../head_pose_estimation_demo.dir/flags.make
CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRForestEstimator.cpp.obj: CMakeFiles/../head_pose_estimation_demo.dir/includes_CXX.rsp
CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRForestEstimator.cpp.obj: C:/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRForestEstimator.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report C:\Users\varsha\Documents\ResearchTools\head_pose_estimation\my_demo_build\CMakeFiles $(CMAKE_PROGRESS_1)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRForestEstimator.cpp.obj"
	C:\MinGW\bin\g++.exe   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles\..\head_pose_estimation_demo.dir\C_\Users\varsha\Documents\ResearchTools\head_pose_estimation\CRForestEstimator.cpp.obj -c C:\Users\varsha\Documents\ResearchTools\head_pose_estimation\CRForestEstimator.cpp

CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRForestEstimator.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRForestEstimator.cpp.i"
	C:\MinGW\bin\g++.exe  $(CXX_DEFINES) $(CXX_FLAGS) -E C:\Users\varsha\Documents\ResearchTools\head_pose_estimation\CRForestEstimator.cpp > CMakeFiles\..\head_pose_estimation_demo.dir\C_\Users\varsha\Documents\ResearchTools\head_pose_estimation\CRForestEstimator.cpp.i

CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRForestEstimator.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRForestEstimator.cpp.s"
	C:\MinGW\bin\g++.exe  $(CXX_DEFINES) $(CXX_FLAGS) -S C:\Users\varsha\Documents\ResearchTools\head_pose_estimation\CRForestEstimator.cpp -o CMakeFiles\..\head_pose_estimation_demo.dir\C_\Users\varsha\Documents\ResearchTools\head_pose_estimation\CRForestEstimator.cpp.s

CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRForestEstimator.cpp.obj.requires:
.PHONY : CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRForestEstimator.cpp.obj.requires

CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRForestEstimator.cpp.obj.provides: CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRForestEstimator.cpp.obj.requires
	$(MAKE) -f CMakeFiles\..\head_pose_estimation_demo.dir\build.make CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRForestEstimator.cpp.obj.provides.build
.PHONY : CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRForestEstimator.cpp.obj.provides

CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRForestEstimator.cpp.obj.provides.build: CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRForestEstimator.cpp.obj

CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRTree.cpp.obj: CMakeFiles/../head_pose_estimation_demo.dir/flags.make
CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRTree.cpp.obj: CMakeFiles/../head_pose_estimation_demo.dir/includes_CXX.rsp
CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRTree.cpp.obj: C:/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRTree.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report C:\Users\varsha\Documents\ResearchTools\head_pose_estimation\my_demo_build\CMakeFiles $(CMAKE_PROGRESS_2)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRTree.cpp.obj"
	C:\MinGW\bin\g++.exe   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles\..\head_pose_estimation_demo.dir\C_\Users\varsha\Documents\ResearchTools\head_pose_estimation\CRTree.cpp.obj -c C:\Users\varsha\Documents\ResearchTools\head_pose_estimation\CRTree.cpp

CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRTree.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRTree.cpp.i"
	C:\MinGW\bin\g++.exe  $(CXX_DEFINES) $(CXX_FLAGS) -E C:\Users\varsha\Documents\ResearchTools\head_pose_estimation\CRTree.cpp > CMakeFiles\..\head_pose_estimation_demo.dir\C_\Users\varsha\Documents\ResearchTools\head_pose_estimation\CRTree.cpp.i

CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRTree.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRTree.cpp.s"
	C:\MinGW\bin\g++.exe  $(CXX_DEFINES) $(CXX_FLAGS) -S C:\Users\varsha\Documents\ResearchTools\head_pose_estimation\CRTree.cpp -o CMakeFiles\..\head_pose_estimation_demo.dir\C_\Users\varsha\Documents\ResearchTools\head_pose_estimation\CRTree.cpp.s

CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRTree.cpp.obj.requires:
.PHONY : CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRTree.cpp.obj.requires

CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRTree.cpp.obj.provides: CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRTree.cpp.obj.requires
	$(MAKE) -f CMakeFiles\..\head_pose_estimation_demo.dir\build.make CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRTree.cpp.obj.provides.build
.PHONY : CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRTree.cpp.obj.provides

CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRTree.cpp.obj.provides.build: CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRTree.cpp.obj

CMakeFiles/../head_pose_estimation_demo.dir/gl_camera.cpp.obj: CMakeFiles/../head_pose_estimation_demo.dir/flags.make
CMakeFiles/../head_pose_estimation_demo.dir/gl_camera.cpp.obj: CMakeFiles/../head_pose_estimation_demo.dir/includes_CXX.rsp
CMakeFiles/../head_pose_estimation_demo.dir/gl_camera.cpp.obj: C:/Users/varsha/Documents/ResearchTools/head_pose_estimation/demo/gl_camera.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report C:\Users\varsha\Documents\ResearchTools\head_pose_estimation\my_demo_build\CMakeFiles $(CMAKE_PROGRESS_3)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object CMakeFiles/../head_pose_estimation_demo.dir/gl_camera.cpp.obj"
	C:\MinGW\bin\g++.exe   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles\..\head_pose_estimation_demo.dir\gl_camera.cpp.obj -c C:\Users\varsha\Documents\ResearchTools\head_pose_estimation\demo\gl_camera.cpp

CMakeFiles/../head_pose_estimation_demo.dir/gl_camera.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../head_pose_estimation_demo.dir/gl_camera.cpp.i"
	C:\MinGW\bin\g++.exe  $(CXX_DEFINES) $(CXX_FLAGS) -E C:\Users\varsha\Documents\ResearchTools\head_pose_estimation\demo\gl_camera.cpp > CMakeFiles\..\head_pose_estimation_demo.dir\gl_camera.cpp.i

CMakeFiles/../head_pose_estimation_demo.dir/gl_camera.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../head_pose_estimation_demo.dir/gl_camera.cpp.s"
	C:\MinGW\bin\g++.exe  $(CXX_DEFINES) $(CXX_FLAGS) -S C:\Users\varsha\Documents\ResearchTools\head_pose_estimation\demo\gl_camera.cpp -o CMakeFiles\..\head_pose_estimation_demo.dir\gl_camera.cpp.s

CMakeFiles/../head_pose_estimation_demo.dir/gl_camera.cpp.obj.requires:
.PHONY : CMakeFiles/../head_pose_estimation_demo.dir/gl_camera.cpp.obj.requires

CMakeFiles/../head_pose_estimation_demo.dir/gl_camera.cpp.obj.provides: CMakeFiles/../head_pose_estimation_demo.dir/gl_camera.cpp.obj.requires
	$(MAKE) -f CMakeFiles\..\head_pose_estimation_demo.dir\build.make CMakeFiles/../head_pose_estimation_demo.dir/gl_camera.cpp.obj.provides.build
.PHONY : CMakeFiles/../head_pose_estimation_demo.dir/gl_camera.cpp.obj.provides

CMakeFiles/../head_pose_estimation_demo.dir/gl_camera.cpp.obj.provides.build: CMakeFiles/../head_pose_estimation_demo.dir/gl_camera.cpp.obj

CMakeFiles/../head_pose_estimation_demo.dir/main.cpp.obj: CMakeFiles/../head_pose_estimation_demo.dir/flags.make
CMakeFiles/../head_pose_estimation_demo.dir/main.cpp.obj: CMakeFiles/../head_pose_estimation_demo.dir/includes_CXX.rsp
CMakeFiles/../head_pose_estimation_demo.dir/main.cpp.obj: C:/Users/varsha/Documents/ResearchTools/head_pose_estimation/demo/main.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report C:\Users\varsha\Documents\ResearchTools\head_pose_estimation\my_demo_build\CMakeFiles $(CMAKE_PROGRESS_4)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object CMakeFiles/../head_pose_estimation_demo.dir/main.cpp.obj"
	C:\MinGW\bin\g++.exe   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles\..\head_pose_estimation_demo.dir\main.cpp.obj -c C:\Users\varsha\Documents\ResearchTools\head_pose_estimation\demo\main.cpp

CMakeFiles/../head_pose_estimation_demo.dir/main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../head_pose_estimation_demo.dir/main.cpp.i"
	C:\MinGW\bin\g++.exe  $(CXX_DEFINES) $(CXX_FLAGS) -E C:\Users\varsha\Documents\ResearchTools\head_pose_estimation\demo\main.cpp > CMakeFiles\..\head_pose_estimation_demo.dir\main.cpp.i

CMakeFiles/../head_pose_estimation_demo.dir/main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../head_pose_estimation_demo.dir/main.cpp.s"
	C:\MinGW\bin\g++.exe  $(CXX_DEFINES) $(CXX_FLAGS) -S C:\Users\varsha\Documents\ResearchTools\head_pose_estimation\demo\main.cpp -o CMakeFiles\..\head_pose_estimation_demo.dir\main.cpp.s

CMakeFiles/../head_pose_estimation_demo.dir/main.cpp.obj.requires:
.PHONY : CMakeFiles/../head_pose_estimation_demo.dir/main.cpp.obj.requires

CMakeFiles/../head_pose_estimation_demo.dir/main.cpp.obj.provides: CMakeFiles/../head_pose_estimation_demo.dir/main.cpp.obj.requires
	$(MAKE) -f CMakeFiles\..\head_pose_estimation_demo.dir\build.make CMakeFiles/../head_pose_estimation_demo.dir/main.cpp.obj.provides.build
.PHONY : CMakeFiles/../head_pose_estimation_demo.dir/main.cpp.obj.provides

CMakeFiles/../head_pose_estimation_demo.dir/main.cpp.obj.provides.build: CMakeFiles/../head_pose_estimation_demo.dir/main.cpp.obj

# Object files for target ../head_pose_estimation_demo
__/head_pose_estimation_demo_OBJECTS = \
"CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRForestEstimator.cpp.obj" \
"CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRTree.cpp.obj" \
"CMakeFiles/../head_pose_estimation_demo.dir/gl_camera.cpp.obj" \
"CMakeFiles/../head_pose_estimation_demo.dir/main.cpp.obj"

# External object files for target ../head_pose_estimation_demo
__/head_pose_estimation_demo_EXTERNAL_OBJECTS =

../head_pose_estimation_demo.exe: CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRForestEstimator.cpp.obj
../head_pose_estimation_demo.exe: CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRTree.cpp.obj
../head_pose_estimation_demo.exe: CMakeFiles/../head_pose_estimation_demo.dir/gl_camera.cpp.obj
../head_pose_estimation_demo.exe: CMakeFiles/../head_pose_estimation_demo.dir/main.cpp.obj
../head_pose_estimation_demo.exe: CMakeFiles/../head_pose_estimation_demo.dir/build.make
../head_pose_estimation_demo.exe: CMakeFiles/../head_pose_estimation_demo.dir/objects1.rsp
../head_pose_estimation_demo.exe: CMakeFiles/../head_pose_estimation_demo.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --red --bold "Linking CXX executable ..\head_pose_estimation_demo.exe"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles\..\head_pose_estimation_demo.dir\link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/../head_pose_estimation_demo.dir/build: ../head_pose_estimation_demo.exe
.PHONY : CMakeFiles/../head_pose_estimation_demo.dir/build

CMakeFiles/../head_pose_estimation_demo.dir/requires: CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRForestEstimator.cpp.obj.requires
CMakeFiles/../head_pose_estimation_demo.dir/requires: CMakeFiles/../head_pose_estimation_demo.dir/C_/Users/varsha/Documents/ResearchTools/head_pose_estimation/CRTree.cpp.obj.requires
CMakeFiles/../head_pose_estimation_demo.dir/requires: CMakeFiles/../head_pose_estimation_demo.dir/gl_camera.cpp.obj.requires
CMakeFiles/../head_pose_estimation_demo.dir/requires: CMakeFiles/../head_pose_estimation_demo.dir/main.cpp.obj.requires
.PHONY : CMakeFiles/../head_pose_estimation_demo.dir/requires

CMakeFiles/../head_pose_estimation_demo.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles\..\head_pose_estimation_demo.dir\cmake_clean.cmake
.PHONY : CMakeFiles/../head_pose_estimation_demo.dir/clean

CMakeFiles/../head_pose_estimation_demo.dir/depend:
	$(CMAKE_COMMAND) -E cmake_depends "MinGW Makefiles" C:\Users\varsha\Documents\ResearchTools\head_pose_estimation\demo C:\Users\varsha\Documents\ResearchTools\head_pose_estimation\demo C:\Users\varsha\Documents\ResearchTools\head_pose_estimation\my_demo_build C:\Users\varsha\Documents\ResearchTools\head_pose_estimation\my_demo_build C:\Users\varsha\Documents\ResearchTools\head_pose_estimation\my_demo_build\head_pose_estimation_demo.dir\DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/../head_pose_estimation_demo.dir/depend

